name: Build

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: ["*"]
  workflow_call:

permissions:
  contents: write

jobs:
  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }} ğŸ›ï¸
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install ğŸ”§
        shell: bash
        run: npm install
      - name: Build ğŸ”§
        run: npm run build:all
      - name: Upload Artifact ğŸš€
        uses: actions/upload-artifact@v4
        with:
          name: vot-${{ matrix.node-version }}
          path: dist/vot*.user.js

  extension:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }} ğŸ›ï¸
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install ğŸ”§
        shell: bash
        run: npm install
      - name: Build extension ğŸ”§
        run: npm run build:ext
      - name: Upload extension artifacts ğŸš€
        uses: actions/upload-artifact@v4
        with:
          name: vot-extension-${{ matrix.node-version }}
          path: |
            dist-ext/vot-extension-chrome-*.crx
            dist-ext/vot-extension-firefox-*.xpi

  bun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      - name: Setup Bun.sh ğŸ›ï¸
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install ğŸ”§
        shell: bash
        run: bun install
      - name: Build ğŸ”§
        run: bun run build:all
      - name: Upload Artifact ğŸš€
        uses: actions/upload-artifact@v4
        with:
          name: vot-bun
          path: dist/vot*.user.js
